version: '3'
services:
  webserver:
    image: nginx:latest
    restart: always
    ports: 
      - 8081:80
    volumes: 
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html/app
    restart: always
    
  php:
    build: ./php
    restart: always
    volumes:
      - ../:/var/www/html/app
    depends_on:
      - webserver